/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predict */
        get: operations["predict_api_v1_predict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_predict_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_api_v1_regions_get"];
        put?: never;
        /** Create Region */
        post: operations["create_region_api_v1_regions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Region */
        get: operations["get_region_api_v1_regions__code__get"];
        /** Update Region */
        put: operations["update_region_api_v1_regions__code__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidence */
        get: operations["list_incidence_api_v1_incidence_get"];
        put?: never;
        /** Create Incidence */
        post: operations["create_incidence_api_v1_incidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidence/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incidence */
        get: operations["get_incidence_api_v1_incidence__record_id__get"];
        /** Update Incidence */
        put: operations["update_incidence_api_v1_incidence__record_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /** Version */
            version: string;
        };
        /** IncidenceRecordCreate */
        IncidenceRecordCreate: {
            /** Regionid */
            regionId: number;
            /** Disease */
            disease: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Cases */
            cases: number;
            /** Rateper100K */
            ratePer100K?: number | null;
            /** Source */
            source?: string | null;
        };
        /** IncidenceRecordRead */
        IncidenceRecordRead: {
            /** Regionid */
            regionId: number;
            /** Disease */
            disease: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Cases */
            cases: number;
            /** Rateper100K */
            ratePer100K?: number | null;
            /** Source */
            source?: string | null;
            /** Id */
            id: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** IncidenceRecordUpdate */
        IncidenceRecordUpdate: {
            /** Cases */
            cases?: number | null;
            /** Rateper100K */
            ratePer100K?: number | null;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Ismock */
            isMock: boolean;
            /** Trainedat */
            trainedAt?: string | null;
        };
        /** PaginatedResponse[IncidenceRecordRead] */
        PaginatedResponse_IncidenceRecordRead_: {
            /** Items */
            items: components["schemas"]["IncidenceRecordRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalpages */
            totalPages: number;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Region */
            region: string;
            /** Disease */
            disease: string;
            model: components["schemas"]["ModelInfo"];
            /** Horizon */
            horizon: number;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Dates */
            dates: string[];
            /** Predictedcases */
            predictedCases: number[];
            /** Cilower */
            ciLower: number[];
            /** Ciupper */
            ciUpper: number[];
        };
        /** RegionCreate */
        RegionCreate: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /**
             * Adminlevel
             * @enum {string}
             */
            adminLevel: "country" | "department" | "province" | "district";
            /** Parentcode */
            parentCode?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Population */
            population?: number | null;
        };
        /** RegionRead */
        RegionRead: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /**
             * Adminlevel
             * @enum {string}
             */
            adminLevel: "country" | "department" | "province" | "district";
            /** Parentcode */
            parentCode?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Population */
            population?: number | null;
            /** Id */
            id: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** RegionUpdate */
        RegionUpdate: {
            /** Name */
            name?: string | null;
            /** Population */
            population?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    predict_api_v1_predict_get: {
        parameters: {
            query: {
                /** @description Nombre del modelo registrado, ej. 'mock' */
                model: string;
                /** @description Codigo de region, ej. 'PE-LIM' */
                region: string;
                disease?: string;
                /** @description Numero de periodos (semanas) a predecir */
                horizon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_predict_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    list_regions_api_v1_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionRead"][];
                };
            };
        };
    };
    create_region_api_v1_regions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_api_v1_regions__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_region_api_v1_regions__code__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidence_api_v1_incidence_get: {
        parameters: {
            query?: {
                regionCode?: string | null;
                disease?: string | null;
                dateFrom?: string | null;
                dateTo?: string | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_IncidenceRecordRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incidence_api_v1_incidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidenceRecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenceRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incidence_api_v1_incidence__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenceRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_incidence_api_v1_incidence__record_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidenceRecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenceRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
